### ISSUE TITLE
Use peer dependencies in "plugins"

### ISSUE THREAD

**Issue by doubret** [rstiller/inspector-metrics#12]
inspector-influx, inspector-elasticsearch, etc... and inspector-vm should declare inspector-metrics as peer dependencies.

not doing causes a lot of troubles when trying to use `instanceof` in the code (this is the cas in inspector-elasticsearch for example).

as there are multiple inspector-metrics modules loaded by node, `instanceof` is "confused" and doesn't match the types as expected.

**Comment by rstiller** [comment]
I'll update the repositories accordingly. Unfortunately I can't merge your pull requests for this topic. Both of them use different package names. I'll publish new versions this afternoon. Sorry for the delay and thanks for pointing out the issue.

**Comment by doubret** [comment]
True, sorry i changed the names for testing. I can push the correct name if on my forks if it helps

**Comment by rstiller** [comment]
for now I added the peer dependency to:
https://github.com/rstiller/inspector-elasticsearch
https://github.com/rstiller/inspector-influx
https://github.com/rstiller/inspector-prometheus
https://github.com/rstiller/inspector-carbon
https://github.com/rstiller/inspector-vm

I will do this for https://github.com/rstiller/inspector-csv this weekend.

I'm closing the pull requests accordingly - I made the changes & publications in one rush - which made the PRs obsolete. I hope you don't mind.
Thanks again.

**Comment by doubret** [comment]
Thanks for the prompt support.
