### ISSUE TITLE
RatioGauge missing

### ISSUE THREAD

**Issue by rburgst** [rstiller/inspector-metrics#15]
In order to record metrics such as cache hit ratio, it would be good to also have a ratio gauge.

https://metrics.dropwizard.io/3.1.0/apidocs/com/codahale/metrics/RatioGauge.html

**Comment by rstiller** [comment]
Thanks for the hint. I will add it this weekend.
Meanwhile you can report such a value like this:

```typescript
const cache = ...
const cacheHitRatioGauge = new SizeGauge("cacheHitRatio", {
    size: () => cache.getHitRequestCount() / cache.getTotalRequestCount()
});
metricRegistry.registerMetric(cacheHitRatioGauge);
```

**Comment by rburgst** [comment]
This will only give me an average cache hit ratio, I am looking for a sliding window.

**Comment by rstiller** [comment]
As far as I can tell RatioGauge from codahale metrics lib wouldn't give that too: https://github.com/dropwizard/metrics/blob/4.1-development/metrics-core/src/main/java/com/codahale/metrics/RatioGauge.java

It's a simple gauge implementation to do a division and do some checks.

What you ask for is a kind of `Histogram` with the cache-hit-ratio for only the last N time-units (e.g. last 30 seconds) - or do I misunderstand you? This would mean that only the changes in values since the last calculation are considered to calculate the ratio !?!?

In this case I would suggest to report the `total` and the `hit` and / or `miss` value as simple gauge and let the time-series DB do the math instead:

```typescript
import { MetricRegistry, SizeGauge } from "inspector-metrics";

const cache = ...
const cacheRequestHitGauge = new SizeGauge("cacheRequestHitsCount", {
    size: () => cache.getHitRequestCount()
});
const cacheRequestTotalGauge = new SizeGauge("cacheRequestTotalCount", {
    size: () => cache.getTotalRequestCount()
});
metricRegistry.registerMetric(cacheRequestHitGauge);
metricRegistry.registerMetric(cacheRequestTotalGauge);
```

What do you think of this?

**Comment by rburgst** [comment]
I think you are correct. The problem is that my trivial sample isnt connected to a time-series DB and therefore, it would have been nice to get something relatively simple.

**Comment by rstiller** [comment]
Hmmm .... this doesn't seem to be a common use case.

In general I try to keep the lib simple and stay away from sources of errors like calculations that are hard to understand and difficult to identify as source of an error.

Therefore I can may be convince you to implement it for your project yourself like this:

```typescript
import {
    Histogram,
    ...
} from "inspector-metrics";

export class RatioHistogram extends Histogram implements BucketCounting, Counting, Metric, Sampling, Summarizing {

    private ratioCalculator: () => number;

    public constructor(
        ratioCalculator: () => number,
        maxValues: number,
        name?: string,
        description?: string,
        buckets: Buckets = new Buckets()) {
        super(new SlidingWindowReservoir(maxValues), name, description, buckets);
        this.ratioCalculator = ratioCalculator;
    }

    public getSnapshot(): Snapshot {
        this.update(this.ratioCalculator());
        return super.getSnapshot();
    }

}

export class RatioCalculator {

    private lastHits: number;
    private lastTotal: number;
    private hitSupplier: () => number;
    private totalSupplier: () => number;

    constructor(
        hitSupplier: () => number,
        totalSupplier: () => number,
    ) {
        this.hitSupplier = hitSupplier;
        this.totalSupplier = totalSupplier;
        this.lastHits = 0;
        this.lastTotal = 0;
    }

    public getRatio(): number {
        const hits = this.hitSupplier();
        const total = this.totalSupplier();

        const hitsToCal = hits - this.lastHits;
        const totalToCal = total - this.lastTotal;

        this.lastHits = hits;
        this.lastTotal = total;

        return hitsToCal / totalToCal;
    }

}

const ratioSupplier = new RatioCalculator(() => caches.getHitCount(), () => caches.getTotalCount());
// holds the 1min cache-hit-ratios for last 24 hours
const cacheHitRatio = new RatioHistogram(() => ratioSupplier.getRatio(), 1440);
const registry = new MetricRegistry();
// the reporter will call the getSnapshot method of the histogram every minute
const reporter = new LoggerReporter({
    log: global.console,
    reportInterval: 1,
    unit: TimeUnit.MINUTE
});

registry.registerMetric(cacheHitRatio);

reporter.addMetricRegistry(registry);
reporter.start();
```

*Disclaimer* I did not test this code and did not address certain aspects of the metric reporting process. Therefore be careful when using it.

How to proceed from here on now?

**Comment by rstiller** [comment]
@rburgst Can I close the ticket or do you have any suggestions how to proceed?

**Comment by rburgst** [comment]
Hi, I can understand that this is beyond the scope of your project. Thanks a log for all the pointers!
