### ISSUE TITLE
`MetricRegistry` is missing `newGauge` method

### ISSUE THREAD

**Issue by dislick** [rstiller/inspector-metrics#19]
![grafik](https://user-images.githubusercontent.com/3121902/67027733-66500d00-f10a-11e9-9e1a-3a79d4c4a31e.png)

I could create a pull request to implement this, but I'm unsure what you think makes more sense @rstiller:

- `newGauge` method that returns a `SimpleGauge`
- `newSimpleGauge` and `newSizeGauge` methods
- both

Thanks for your work and I'd appreciate a quick feedback.

**Comment by rstiller** [comment]
Hi,

this is on purpose since Gauge is an interface. Gauge implementations (e.g. SimpleGauge) are only registered using the `registerMetric` function.

**Comment by dislick** [comment]
Okay, thanks!
