### ISSUE TITLE
Histogram size maxes out at 1024

### ISSUE THREAD

**Issue by roblav96** [rstiller/inspector-metrics#2]
I'm getting a snapshot like so:
```typescript
let snapshot = this.histogram.getSnapshot()
return {
	size: snapshot.size(),
	mean: snapshot.getMean(),
	median: snapshot.getMedian(),
	stdDev: snapshot.getStdDev(),
	min: snapshot.getMin(),
	max: snapshot.getMax(),
	p75: snapshot.get75thPercentile(),
	p95: snapshot.get95thPercentile(),
	p98: snapshot.get98thPercentile(),
	p99: snapshot.get99thPercentile(),
	p999: snapshot.get999thPercentile(),
}
```
And the `size` method never wants to go any higher than `1024`.

----

![metrics](https://i.imgur.com/osPETH4.png)

**Comment by rstiller** [comment]
Hi,
have a look at https://github.com/rstiller/inspector-influx/blob/master/lib/metrics/InfluxMetricReporter.ts#L197

The size gives you back the amount of measure points the reservoir is currently holding.
I think you want to use the `getCount()` method of Histogram to get the total number of measure points.

**Comment by roblav96** [comment]
I initially thought to use the `getCount` method but it does not exist on `snapshot`.

----

![](https://i.imgur.com/8v3oozR.png)

**Comment by rstiller** [comment]
`this.histogram.getCount()` does the trick

**Comment by rstiller** [comment]
Does it solve the issue? Can I close the ticket or do have any questions?

**Comment by rstiller** [comment]
If there anything left to do for me here - let me know.
Also feel free to reopen the ticket.

**Comment by roblav96** [comment]
@rstiller Hey sorry, yes this does the magic =]
