### ISSUE TITLE
Example is obsolete ?

### ISSUE THREAD

**Issue by doubret** [rstiller/inspector-metrics#5]
I'm trying to use the reporter as in the example you provided :

`const reporter = new LoggerReporter(global.console);`

It doesn't compile.
The signature of the constructor is not compliant.

Thanks

**Comment by rstiller** [comment]
Hi,

I'm sorry for the inconvenience.

Thank you for pointing out this bug.
I fixed it and release a new version, so the npm page is fixed too.

Feel free to reopen this issue if you see more bugs in the readme examples.

**Comment by doubret** [comment]
Thanks.
