### ISSUE TITLE
InfluxDB 2

### ISSUE THREAD

**Issue by jamesholcomb** [rstiller/inspector-metrics#56]
Are there plans to support v2?  I believe refactoring to https://github.com/influxdata/influxdb-client-js for token auth may be necessary.

**Comment by rstiller** [comment]
Not yet. But I will have a look this week(end) and see if a new reporter-package is necessary to support both major versions of influxdb.

**Comment by jamesholcomb** [comment]
I took a crack at it...wip and have tested with Events only so far.

https://github.com/bitscheme/inspector-metrics/tree/influxdb-v2

Please let me know if you'd like a PR.

**Comment by rstiller** [comment]
I think I would like you to create a PR for it - not everything need to work right away.
But I want to support influx < 1.8 and therefore need to support `node-influx` package.
So after merging I will add support for the legacy package and tune the tests and examples accordingly.
After this is done I will do a release.

Is this OK for you or do you need it very soon?

**Comment by jamesholcomb** [comment]
At your convenience is fine...I wrote the code for a prototype I was building so I do not need it published.

Since you will have some reorganization to do in the workspace for concurrent 1.8 and 2.0 compat, it makes more sense for you to take my wip from `inspector-influx` and go from there.

**Comment by rstiller** [comment]
I've just release version 2.9.0 of `inspector-influx` alongside the updated documentation: https://rstiller.github.io/inspector-metrics/additional-documentation/inspector-influx.html (could take a few hours to update the cache docs)

Feel free to reopen the issue in case an error shows up.

Sorry for the long delay!
