### ISSUE TITLE
Can you remove import 'source-map-support/register' from files

### ISSUE THREAD

**Issue by polRk** [rstiller/inspector-metrics#70]
I cannot bundle my app for edge functions

**Comment by rstiller** [comment]
We're talking about AWS Lamdas, right?

Is the dependency `source-map-support` the problem or the ES6-style import statement?
I would like to keep the source map support for better debugging and error traces.

**Comment by polRk** [comment]
Cloudflare workers

**Comment by rstiller** [comment]
This lib is may be not the right choice for short lived applications. You could use a client lib of your time-series server instead to sent metrics data to it.

In any case you can fork it and modify it as needed.
